#!/usr/bin/env python
# encoding: utf-8
"""
045 - Tri Pent Hex Numbers.py

Created by Jason Sundram on 2009-12-06.

Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:
Triangle        T_(n)=n(n+1)/2      1, 3, 6, 10, 15, ...
Pentagonal      P_(n)=n(3n−1)/2     1, 5, 12, 22, 35, ...
Hexagonal       H_(n)=n(2n−1)       1, 6, 15, 28, 45, ...

It can be verified that T_(285) = P_(165) = H_(143) = 40755.

Find the next triangle number that is also pentagonal and hexagonal.

::http://www.wolframalpha.com/input/?i=h%282*h-1%29+%3D+%28t*t+%2B+t%29%2F2+%3D+%283*p*p+-+p%29+%2F+2
"""

from timed import timed

def penta(n):
    return n * (3 * n - 1) / 2

def hexa(n):
    return n * (2 * n - 1)
    
def tri(n):
    return n * (n + 1) / 2
    
@timed
def original_solution():
    (t, p, h) = (285, 165, 144) # h is one past the first solution
    while True:
        H = hexa(h)
        
        while tri(t) < H:
            t += 1
        while penta(p) < H:
            p += 1
        
        if tri(t) == penta(p) == H: 
            print "t,p,h = (%d, %d, %d) => %d" % (t,p,h,H)
            return H
        
        h += 1
        
    return -1


def main():
    print 'The answer (original) is: %d' % original_solution()


if __name__ == '__main__':
	main()


